name: GCB Build in Android

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build for Android
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache Library
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ runner.os }}-${{ github.run_id }}
          restore-keys: |
            Library-${{ runner.os }}-

      - name: Setup Unity
        uses: game-ci/unity-builder@v4.3.0
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          unityVersion: 2022.3.10f1  # Unityの正しいバージョンに変更
          targetPlatform: Android

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Build-Android-${{ github.sha }}
          path: build
